---
abstract: 'remove duplicated entries from feed'
author:
  - 'Tokuhiro Matsuno <tokuhirom  slkjfd gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Feed-Deduper
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.06
  DB_File: 0
  Filter::Util::Call: 0
  XML::Feed: 0.41
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
