---
abstract: 'remove duplicated entries from feed'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom  slkjfd@ gmail.comE<gt>'
build_requires:
  Test::More: 0.98
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Feed-Deduper
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  XML::Feed::Deduper:
    file: lib/XML/Feed/Deduper.pm
    version: 0.05
  XML::Feed::Deduper::DB_File:
    file: lib/XML/Feed/Deduper/DB_File.pm
    version: 0
  XML::Feed::Deduper::Role:
    file: lib/XML/Feed/Deduper/Role.pm
    version: 0
requires:
  Any::Moose: 0.1
  DB_File: 0
  XML::Feed: 0.41
  perl: v5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
